version: '3'
services:
  node:
    build: .
    container_name: test-stitcher-service
    ports:
      - target: 3333
        published: 5100
    working_dir: /app
    volumes:
      # Mount the source code into the container, so one can keep developing, even though it runs inside a container.
      - '.:/app'
    tty: true
    command: ["bash"]
